### ISSUE TITLE
Classes from packages different than js-joda/core

### ISSUE THREAD

**Issue by unmonoqueteclea** [henryw374/cljs.java-time#6]
As far as I know, this library only offers methods from `js-joda/core` package.
However, js-joda contains three more packages:

- `@js-joda/timezone `
- `@js-joda/locale `
- `@js-joda/extra`

I can help to add them, but I am not sure about how to start. If you could give me a piece of advise, I could try to add the missing packages, as I already did with some of the missing packages from js-joda/core

I think my issue is related to #1, but is there any workaround?

Thanks!

**Comment by henryw374** [comment]
hi. tick makes use of timezone and locale packages. see https://github.com/juxt/tick/blob/master/docs/cljs.adoc for info. for timezone you just require it, and on load it extends the capabilities of jsjoda, so jsjoda then knows about zones . for locale,  see for example in https://github.com/juxt/tick/blob/master/src/tick/format.cljc how it gets hold of the locale object. but that's all you need to do really. 

for extra, that would be more code like in the java/time.cljs package here, so there's something to do there for sure. 

at the moment this lib assumes non-shadow, see the cljs doc in tick above for link to a demo project using shadow, and what you have to do to make that work. hope this helps for starters!

**Comment by unmonoqueteclea** [comment]
Thank you for your response!

I need Locale/EN and Locale/US, so I took the `java/time.cljs` approach and I did:

```clujre
(ns java.locale
  (:require
   [cljsjs.js-joda-locale-en-us :as locale]))

(def Locale (.. locale -Locale))
```

In the same way as it's done in java/time/format.cljs I want to add a folder called temporal in locale to import the `WeekFields` class from js-joda-locale-en-us.


I also added 
`cljsjs/js-joda-locale-en-us {:mvn/version "2.0.0-0"}`
to **deps.edn**, within `:deps`

But I am not able to make it work. Am I missing something? As you can see, I am an absolute beginner with ClojureScript

**Comment by henryw374** [comment]
sorry, pretty busy at the mo... 

(-> js/JSJoda .-IsoFields) is there, but (-> js/JSJoda .-WeekFields) is not. although it looks like the latest version has it: https://js-joda.github.io/js-joda/class/packages/locale/src/temporal/WeekFields.js~WeekFields.html

so it looks like a js-joda upgrade is required. do that either via cljsjs or start using shadow. if you want to hire in help with any of this, I'd be happy to discuss that ;-)

**Comment by unmonoqueteclea** [comment]
Thank you very much, I had to start with a different project and this one is temporally stopped but I will try to return as soon as possible.

**Comment by henryw374** [comment]
fyi there's a new cljs release coming  - as a result of which I'll do a release. not much will change - just the js-joda require statement e.g. https://clojure.atlassian.net/browse/CLJS-3138

**Comment by henryw374** [comment]
0.1.16 now released, with updated js-joda dep

**Comment by henryw374** [comment]
pls reopen if more activity
