### ISSUE TITLE
LICENSE & website missing from pom.xml

### ISSUE THREAD

**Issue by SevereOverfl0w** [henryw374/cljs.java-time#9]
This stops automatic tools from picking it up.

**Comment by RickMoynihan** [comment]
Just came here to report this, and found this issue already here.

The new tool that reports this is `clj -X:deps list` which was released today.

**Comment by henryw374** [comment]
looks like tools.build does not support license yet https://clojure.org/guides/tools_build

nor does the applied-science tool I was using.

**Comment by SevereOverfl0w** [comment]
tools.build supports a `:src-pom`, which can have the LICENSE in.

**Comment by henryw374** [comment]
now fixed. 

note this repo is released under a new name: https://clojars.org/com.widdindustries/cljs.java-time

I will be updating tick etc with this shortly
